In [1]:
def test():
        print('Test() for the function')
        return
test()

Test() for the function


In [8]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [13]:
class Demo:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p=Demo()
print(p.fact(5))
print(p.fact(7))
print(p.fact(8))

120
5040
40320


In [21]:
class Demo:
    def _init_(self,p,p1):
        self.p=p
        self.p1=p1
    def add(self,p,p1):
        return p+p1
c=Demo()
print(c.add(100,200))

300


In [ ]:
class person(object):
    def _init_(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemploy(self):
        return False


In [5]:
import numpy as np
a1= np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [10]:
a1=np.random.normal(5,5,8)
print(a1)

[ 4.22026921  8.26353678  2.89177083 10.439428   -0.9830407   3.71174367
  6.95396516  4.52876306]


In [ ]:
a=np.matrix(np.ones(4,4),dtype=np.int(64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing last Colum:",a1[:1])

Slicing last Colum: [[1 2 3]]


In [13]:
a1=np.random.normal(5,1,10)
print(a1)

[4.62016492 4.34638265 3.83332138 3.99994821 7.12913392 4.34214194
 4.23328678 4.70459771 5.23348353 5.59286943]


In [18]:
a1=np.random.normal(5,1,10)
print(a1)
print("max Value=",np.max(a1))
print("mix Value=",np.min(a1))
print("mean Value=",np.mean(a1))
print("median Value=",np.median(a1))

[4.95500948 4.00598766 5.34724577 6.72863006 5.86235199 5.64843712
 6.474639   4.25732847 5.27684537 4.29169322]
max Value= 6.728630061903983
mix Value= 4.005987660986278
mean Value= 5.284816813653751
median Value= 5.312045571910394


In [19]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(2,5),(8,7)])
np.dot(c1,c2)

array([[18, 19],
       [38, 43]])

In [20]:
c1=np.array([1,2])
c2=np.array([2,5])
np.dot(c1,c2)

12

In [21]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(2,5),(8,7)])
np.matmul(c1,c2)

array([[18, 19],
       [38, 43]])

In [24]:
c1=np.array([1,2,3,5,8])
c2=np.array([0,3,4,2,1])
c=c1+c2
c=c*c1
print(c[2])

21


In [8]:
import pandas as pd
dict={"Name":["dkdkpkd","hadhiadl","jasidjiasjd","ajdjshdjahdl"],
      "Emailid":["ajjraojoa@gmail.com","asjdasdkljadj@gmail.com","ahsfiahsihai@gmail.com","ddughaukdghadgh@gmail.com"],
      "Number":["565136646464","765476546553","697634646343","4357646478664"]}
b=pd.DataFrame(dict)
print(b)

           Name                    Emailid         Number
0       dkdkpkd        ajjraojoa@gmail.com   565136646464
1      hadhiadl    asjdasdkljadj@gmail.com   765476546553
2   jasidjiasjd     ahsfiahsihai@gmail.com   697634646343
3  ajdjshdjahdl  ddughaukdghadgh@gmail.com  4357646478664


In [9]:
b.index=["01","02","03","04"]
print(b)

            Name                    Emailid         Number
01       dkdkpkd        ajjraojoa@gmail.com   565136646464
02      hadhiadl    asjdasdkljadj@gmail.com   765476546553
03   jasidjiasjd     ahsfiahsihai@gmail.com   697634646343
04  ajdjshdjahdl  ddughaukdghadgh@gmail.com  4357646478664


In [3]:
str="213abc456def111"
for i in range(10):
    x=0
    for j in str:
        if j.isdigit():
            if i==int(j):
                x=x+1
    print(x)

0
4
1
1
1
1
1
0
0
0
